-- Phase 5 deliberately starts with normalized relational tables.
-- The same relationships will later become Hibernate/JPA mappings.

DROP VIEW IF EXISTS v_department_payroll;
DROP VIEW IF EXISTS v_employee_project;
DROP TABLE IF EXISTS employee_project;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS department;

CREATE TABLE department (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    CONSTRAINT uq_department_name UNIQUE (name)
);

CREATE TABLE employee (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INTEGER NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(160) NOT NULL,
    salary DECIMAL(12, 2) NOT NULL,
    hired_on DATE NOT NULL,
    CONSTRAINT uq_employee_email UNIQUE (email),
    CONSTRAINT ck_employee_salary CHECK (salary > 0),
    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id) REFERENCES department (id)
);

CREATE TABLE project (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    budget DECIMAL(14, 2) NOT NULL,
    CONSTRAINT uq_project_name UNIQUE (name),
    CONSTRAINT ck_project_budget CHECK (budget > 0)
);

-- This junction table models the many-to-many relationship between employees
-- and projects. Its composite primary key prevents duplicate assignments.
CREATE TABLE employee_project (
    employee_id INTEGER NOT NULL,
    project_id INTEGER NOT NULL,
    assignment_role VARCHAR(80) NOT NULL,
    hours_per_week DECIMAL(5, 2) NOT NULL,
    assigned_on DATE NOT NULL,
    CONSTRAINT pk_employee_project PRIMARY KEY (employee_id, project_id),
    CONSTRAINT ck_assignment_hours CHECK (hours_per_week > 0 AND hours_per_week <= 40),
    CONSTRAINT fk_assignment_employee
        FOREIGN KEY (employee_id) REFERENCES employee (id),
    CONSTRAINT fk_assignment_project
        FOREIGN KEY (project_id) REFERENCES project (id)
);

-- Foreign-key columns are common join/filter columns, so indexes make those
-- operations cheaper as the tables grow. Unique constraints also create
-- indexes for email, department name, and project name.
CREATE INDEX idx_employee_department ON employee (department_id);
CREATE INDEX idx_employee_project_project ON employee_project (project_id);

-- A view stores a reusable SELECT definition, not a second copy of the data.
CREATE VIEW v_employee_project AS
SELECT
    e.id AS employee_id,
    e.full_name AS employee_name,
    d.name AS department_name,
    p.id AS project_id,
    p.name AS project_name,
    ep.assignment_role,
    ep.hours_per_week
FROM employee_project ep
JOIN employee e ON e.id = ep.employee_id
JOIN department d ON d.id = e.department_id
JOIN project p ON p.id = ep.project_id;

CREATE VIEW v_department_payroll AS
SELECT
    d.id AS department_id,
    d.name AS department_name,
    COUNT(e.id) AS employee_count,
    COALESCE(SUM(e.salary), 0) AS total_salary,
    COALESCE(AVG(e.salary), 0) AS average_salary
FROM department d
LEFT JOIN employee e ON e.department_id = d.id
GROUP BY d.id, d.name;
